services:
  - type: web
    name: analizza-bot
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium && playwright install-deps chromium
    startCommand: gunicorn main:app --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: ANALIZZA_USUARIO
        value: remove
      - key: ANALIZZA_SENHA
        value: 291185
